name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/image/logo.png
    - assets/image/logo2.png
    - assets/image/negativo.png
    - assets/image/contas.png
    - assets/image/competitivas.png
    - assets/image/1contato.png
    - assets/image/2parceria.png
    - assets/image/3pedido.png
    - assets/image/4liberaçao.png

